BookStore/Areas/Admin/Controllers/ProductController.cs
using BookStore.Database;
using BookStore.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore.Query.Internal;

namespace BookStore.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProductController : Controller
    {
        private readonly AppDbContext _db;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public ProductController(AppDbContext db, IWebHostEnvironment webHostEnvironment)
        {
            _db = db;
            _webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Index()
        {
            var UrunlerList = _db.Urunler.ToList();
            return View(UrunlerList);
        }

        public IActionResult Upsert(int? id)
        {
            Product urun = new Product();
            IEnumerable<SelectListItem> CategoryList =_db.Kategori.ToList().Select(
                u => new SelectListItem
                {
                    Text =u.Name,
                    Value = u.Id.ToString(),    
                });

            if (id == null)
            {
                ViewBag.Kategoriler = CategoryList;
                return View(urun);
            }
            else
            {
                ViewBag.Kategoriler = CategoryList;
                var urunfromdb = _db.Urunler.FirstOrDefault(k => k.Id == id);
                return View(urunfromdb);
            }
      
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(Product urun, IFormFile? file)
        {
            if (ModelState.IsValid)
            {
                string wwRootPath = _webHostEnvironment.WebRootPath;
                if(file != null)
                {
                    string fileName = Guid.NewGuid().ToString();
                    var uploads = Path.Combine(wwRootPath, @"Images\Products");
                    var extension = Path.GetExtension(file.FileName);

                    if(urun.ImageUrl != null)
                    {
                        var oldImagePath = Path.Combine(wwRootPath, urun.ImageUrl.TrimStart('\\'));
                        if (System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    }

                    using (var fileStreams = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                    {
                        file.CopyTo(fileStreams);
                    }
                    urun.ImageUrl = @"\Images\Products\" + fileName + extension;
                }
                if(urun.Id == 0)
                {
                    _db.Urunler.Add(urun);
                    TempData["success"] = "Ürün başarıyla eklendi.";
                }
                else
                {
                    _db.Urunler.Update(urun);
                    TempData["success"] = "Ürün başarıyla güncellendi.";
                }
                _db.SaveChanges();
                
                return RedirectToAction("Index");
            }
            return View(urun);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var urunFromDB = _db.Urunler.FirstOrDefault(k => k.Id == id);
            if (urunFromDB == null)
            {
                return NotFound();
            }
            return View(urunFromDB);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var obj = _db.Urunler.Find(id);
            var oldImagePath = Path.Combine(_webHostEnvironment.WebRootPath, obj.ImageUrl.TrimStart('\\'));
            if (System.IO.File.Exists(oldImagePath))
            {
                System.IO.File.Delete(oldImagePath);
            }
            _db.Urunler.Remove(obj);
            _db.SaveChanges();
            TempData["success"] = "Ürün başarıyla silindi.";
            return RedirectToAction("Index");

        }
    }
}

BookStore/Areas/User/Controllers/CartController.cs
using BookStore.Database;
using BookStore.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace BookStore.Areas.User.Controllers
{
    [Area("User")]
    [Authorize]
    public class CartController : Controller
    {
        private readonly AppDbContext _db;

        public int Total;

        public CartController(AppDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {   double total = 0;
            List<ShoppingCart> carts = _db.ShoppingCart.Include(u=>u.product).ToList();
            foreach (ShoppingCart cart in carts)
            {
                cart.PriceTotal += (cart.product.Price * cart.count);
                total += cart.PriceTotal;
            }
            TempData["Total"] = total;
            return View(carts);
        }

        public IActionResult Remove(int cartId)
        {
            double total = 0;
            var cart2 = _db.ShoppingCart.FirstOrDefault(u => u.Id == cartId);
            _db.ShoppingCart.Remove(cart2);
            _db.SaveChanges();
            List<ShoppingCart> carts = _db.ShoppingCart.Include(u => u.product).ToList();
            return RedirectToAction(nameof(Index));
        }
    }
}

BookStore/Controllers/CategoryController.cs
using BookStore.Database;
using BookStore.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Query.Internal;

namespace BookStore.Controllers
{
    public class CategoryController : Controller
    {
        private readonly AppDbContext _db;

        public CategoryController(AppDbContext db)
        {
            _db = db;   
        }

        public IActionResult Index()
        {
            var CategoryList = _db.Kategori.ToList();
            return View(CategoryList);
        }
        public IActionResult Create()
        {
           
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category kategori)
        {
            if (ModelState.IsValid)
            {
                _db.Kategori.Add(kategori);
                _db.SaveChanges();
                TempData["success"] = "Kategori başarıyla oluşturuldu.";
                return RedirectToAction("Index");
            }
            return View(kategori);
        }

        public IActionResult Edit(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }
            var categoryFromDb = _db.Kategori.FirstOrDefault(k => k.Id == id);
            if (categoryFromDb == null)
            {
                return NotFound();
            }
            return View(categoryFromDb);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Category kategori)
        {
            if (ModelState.IsValid)
            {
                _db.Kategori.Update(kategori);
                _db.SaveChanges();
                TempData["success"] = "Kategori başarıyla güncellendi.";
                return RedirectToAction("Index");
            }
            return View(kategori);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var categoryFromDb = _db.Kategori.FirstOrDefault(k => k.Id == id);
            if (categoryFromDb == null)
            {
                return NotFound();
            }
            return View(categoryFromDb);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var obj = _db.Kategori.Find(id);
            _db.Kategori.Remove(obj);
            _db.SaveChanges();
            TempData["success"] = "Kategori başarıyla silindi.";
            return RedirectToAction("Index");
        
        }
    }
}

BookStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/Theme.css/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BookStore.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BookStore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-info" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-info" asp-area="Admin" asp-controller="Category" asp-action="Index">Kategori</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-info" asp-area="Admin" asp-controller="Product" asp-action="Index">Ürünler</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="User" asp-controller="Cart" asp-action="Index">
                                <i class="bi bi-basket2-fill" style="color:red"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <partial name="_LoginPartial"/>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notifications" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - BookStore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BookStore/Views/Shared/_Notifications.cshtml
@if(TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}